# Site settings
title: ETEControll
email: gsaneamentoambiental@gmail.com
description: >
  Site da ferramenta ETEControll utilizada para auxiliar o processo em Estações de Tratamento de Efluentes.

baseurl: &baseurl "/ETEControll" # the subpath of your site, e.g. /blog/
url: https://saneamentoambiental.github.io/ETEControll # the base hostname & protocol for your site
git_address: https://github.com/saneamentoambiental/ETEControll
git_edit_address: https://github.com/saneamentoambiental/ETEControll

# theme options from https://bootswatch.com/
# comment out this to use default Bootstrap
bootwatch: paper

# Build settings
markdown: kramdown
highlighter: rouge
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-scholar

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
timezone: Europe/Berlin
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: blog

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true


scholar:
  style: apa
  sort_by: author
  relative: "/ETEControll/referencias.html"
  bibliography_template: <abbr>[{{key}}]</abbr>{{reference}}