title: "Manual de Sobrevivência"
description: "Como sobreviver dentro do curso de Sistemas de Informação do IFS"
author: John Smith
logo: /static/img/avatar.png
github: https://github.com/CaioAReis/hcz-jekyll-blog
about:

baseurl: "/manual-sobrevivencia-site"
url: #

allowsearch: true

disqus_shortname: 
google_analytics: 

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []


paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown


collections:
  category:
    output: true


plugins:
  - jekyll-youtube
  - jekyll-paginate
  - jekyll-gist
  - premonition
  - jekyll-auto-image

# Imagem padrão para os posts.
image: /static/img/placeholder.jpg